[package]
name = "csview"
version = "0.3.3"
authors = ["Wenxuan Zhang <wenxuangm@gmail.com>"]
description="A high performance csv viewer with cjk/emoji support."
categories = ["command-line-utilities"]
homepage = "https://github.com/wfxr/csview"
keywords = [
    "csv",
    "pager",
    "viewer",
    "tool",
]
readme = "README.md"
license = "MIT/Apache-2.0"
exclude = [
    "/completions"
]
repository = "https://github.com/wfxr/csview"
edition = "2018"
build = "build.rs"

[target.'cfg(target_family = "unix")'.dependencies]
nix = "0.18"

[dependencies]
csv = "1.1"
prettytable-rs = "^0.8"
structopt = { version = "0.3", features = ["wrap_help"] }

[profile.release]
lto = true
codegen-units = 1

[build-dependencies]
structopt = "0.3"
